//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirprtInventory.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction()
        {
            this.Transactions1 = new HashSet<Transaction>();
        }
    
        public int Transaction_Id { get; set; }
        public bool Transaction_Type { get; set; }
        public System.DateTime Transaction_DateTime { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> Transaction_Parent_Id { get; set; }
        public int Airport_Id { get; set; }
        public Nullable<int> Aircraft_Id { get; set; }
    
        public virtual Aircraft Aircraft { get; set; }
        public virtual Airport Airport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions1 { get; set; }
        public virtual Transaction Transaction1 { get; set; }
    }
}
